name: my_finance_tracker
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.16.0
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.66.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
